const DEMO_BIRDS=[
 {id:"oriental-stork",name:"东方白鹳",latin:"Ciconia boyciana",group:"鹳科 · 国家一级保护动物",color:"#2f7a74",illustration:"assets/illustrations/oriental-stork.png",photo:"assets/references/oriental-stork.jpg",credit:"Ltshears · CC BY-SA 3.0",source:"https://commons.wikimedia.org/wiki/File:Oriental_Stork.jpg",story:"黑白分明的大型涉禽。四月，它正沿中国东部湿地一路北上，飞回东北平原繁殖。",tags:["黑色长喙","红色眼圈","黑色飞羽"],points:[[1,116,29,"长江中下游","东北平原"],[4,120,38,"华东沿海—华北湿地","东北平原"],[7,131,48,"黑龙江—乌苏里江流域","辽河—渤海湾"],[10,121,37,"渤海湾","长江中下游"]]},
 {id:"spoon-billed-sandpiper",name:"勺嘴鹬",latin:"Calidris pygmaea",group:"鹬科 · 国家一级保护动物",color:"#d86f4b",illustration:"assets/illustrations/spoon-billed-sandpiper.png",photo:"assets/references/spoon-billed-sandpiper.jpg",credit:"tareq's Photography · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Spoon-billed_sandpiper.jpg",story:"只有手掌大小的极危滨鸟。春秋两季，它高度依赖黄海潮间带补充能量，勺形嘴是最醒目的辨识特征。",tags:["勺形嘴","体长约15厘米","潮滩觅食"],points:[[1,96,17,"缅甸与孟加拉湾","华南沿海"],[4,112,25,"华南沿海","江苏潮滩"],[7,174,66,"楚科奇半岛","黄海沿岸"],[10,112,25,"华南—北部湾","东南亚越冬地"]]},
 {id:"beijing-swift",name:"北京雨燕",latin:"Apus apus pekinensis",group:"雨燕科 · 北京代表性候鸟",color:"#7a8e58",illustration:"assets/illustrations/beijing-swift.png",photo:"assets/references/beijing-swift.jpg",credit:"Shouyong & Linda Wong · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Apus_apus_Pekinensis_(Beijing_Swifts)_observed_near_Wulongting,_Beihai_Park,_Beijing,_China.jpg",story:"为飞翔而生的城市候鸟。四月回到北京古建檐下繁殖，秋天沿中亚和西亚一路飞向非洲南部。",tags:["镰刀形长翼","浅叉尾","古建巢址"],points:[[1,23,-22,"非洲南部","东非"],[4,75,26,"西亚—中亚","北京"],[7,116,40,"北京及华北","中亚"],[10,43,8,"东非","非洲南部"]]},
 {id:"bar-headed-goose",name:"斑头雁",latin:"Anser indicus",group:"鸭科 · 高原迁徙代表",color:"#ba8850",illustration:"assets/illustrations/bar-headed-goose.png",photo:"assets/references/bar-headed-goose.jpg",credit:"Charles J. Sharp · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Bar-headed_geese_(Anser_indicus).jpg",story:"穿越高山的耐力飞行家。春季从南亚低地北返，跨过喜马拉雅山脉，在青藏高原湖泊繁殖。",tags:["两道黑色头纹","橙黄色嘴足","高海拔迁徙"],points:[[1,78,25,"印度北部","喜马拉雅南缘"],[4,84,29,"喜马拉雅山脉","青藏高原"],[7,99,37,"青海湖及高原湿地","高原南部"],[10,88,29,"青藏高原南缘","印度北部"]]}
];
const LAYOUT_COPY={a:["方案 A","像翻开一本会动的自然图鉴：先看迁徙全貌，再认识一只鸟。","建议用于公众科普首页"],b:["方案 B","让一只鸟成为主角：插图先建立情感，再用小地图讲清它飞过哪里。","适合儿童、家庭与内容传播"],c:["方案 C","把路线、照片与科普证据放在同一张观察台上，信息密度更高。","适合学校、展馆与研究合作"]};
let demoState={layout:"a",bird:"oriental-stork",month:4,playing:false,timer:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function project(lng,lat){return[(lng+180)/360*1000,(90-lat)/180*520]}
function pathRing(ring){return ring.map((p,i)=>`${i?'L':'M'}${project(p[0],p[1]).map(n=>n.toFixed(1)).join(' ')}`).join(' ')+'Z'}
function geoPath(g){if(!g)return'';if(g.type==='Polygon')return g.coordinates.map(pathRing).join(' ');if(g.type==='MultiPolygon')return g.coordinates.flatMap(p=>p.map(pathRing)).join(' ');return''}
async function drawCountries(){const data=await fetch('assets/data/countries.geojson').then(r=>r.json());$('#countryLayer').innerHTML=data.features.map(f=>`<path class="country ${f.properties.ADMIN==='China'?'china':''}" d="${geoPath(f.geometry)}"><title>${f.properties.ADMIN||''}</title></path>`).join('')}
function positionAt(b,m){let pts=b.points,prev=pts[pts.length-1],next=pts[0];for(let i=0;i<pts.length;i++){if(pts[i][0]<=m)prev=pts[i];if(pts[i][0]>m){next=pts[i];break}}let s=prev[0],e=next[0],c=m;if(e<=s)e+=12;if(c<s)c+=12;let t=(c-s)/(e-s),lng1=prev[1],lng2=next[1];if(Math.abs(lng2-lng1)>180){if(lng2<lng1)lng2+=360;else lng1+=360}let lng=lng1+(lng2-lng1)*t;if(lng>180)lng-=360;let lat=prev[2]+(next[2]-prev[2])*t;return{xy:project(lng,lat),location:t<.5?prev[3]:next[3],next:t<.5?prev[4]:next[4]}}
function routePath(b){return b.points.map((p,i)=>{let q=project(p[1],p[2]),breakLine=i&&Math.abs(q[0]-project(b.points[i-1][1],b.points[i-1][2])[0])>500;return`${i&&!breakLine?'L':'M'}${q[0].toFixed(1)} ${q[1].toFixed(1)}`}).join(' ')}
function icon(id){return`<svg viewBox="0 0 64 64"><use href="#icon-${id}"/></svg>`}
function renderMap(){let selected=DEMO_BIRDS.find(b=>b.id===demoState.bird);$('#demoRouteLayer').innerHTML=DEMO_BIRDS.map(b=>`<path class="demo-route ${b.id===selected.id?'active':''}" d="${routePath(b)}" stroke="${b.color}"/>`).join('');$('#demoMarkerLayer').innerHTML=DEMO_BIRDS.map(b=>{let p=positionAt(b,demoState.month);return`<g class="map-marker" data-id="${b.id}" transform="translate(${p.xy[0].toFixed(1)} ${p.xy[1].toFixed(1)})"><circle r="20" stroke="${b.color}"/><use href="#icon-${b.id}" x="-13" y="-13" width="26" height="26" color="${b.color}"/><text y="33" fill="${b.color}">${b.name}</text></g>`}).join('');$$('.map-marker').forEach(m=>m.addEventListener('click',()=>{demoState.bird=m.dataset.id;render()}))}
function renderProfile(){let b=DEMO_BIRDS.find(x=>x.id===demoState.bird),p=positionAt(b,demoState.month);$('#heroIllustration').src=b.illustration;$('#heroIllustration').alt=`${b.name}原创科普插图`;$('#heroIcon').innerHTML=icon(b.id);$('#heroIcon').style.color=b.color;$('#heroGroup').textContent=b.group;$('#heroName').textContent=b.name;$('#heroLatin').textContent=b.latin;$('#heroStory').textContent=b.story;$('#heroLocation').textContent=p.location;$('#heroNext').textContent=p.next;$('#featureTags').innerHTML=b.tags.map(t=>`<span>${t}</span>`).join('')}
function renderRail(){$('#speciesRail').innerHTML=DEMO_BIRDS.map(b=>`<button class="species-pill ${b.id===demoState.bird?'active':''}" data-id="${b.id}" style="--bird:${b.color}">${icon(b.id)}<span><b>${b.name}</b><small>${b.latin}</small></span></button>`).join('');$$('.species-pill').forEach(p=>p.addEventListener('click',()=>{demoState.bird=p.dataset.id;render()}))}
function renderAssets(){$('#assetGrid').innerHTML=DEMO_BIRDS.map(b=>`<article class="asset-card"><div class="asset-visual"><img src="${b.photo}" alt="${b.name}开放授权参考照片"><img src="${b.illustration}" alt="${b.name}原创科普插图"></div><div class="asset-card-copy"><h3>${b.name}</h3><p>大图：参考照片 · ${b.credit}<br>小图：本项目原创科普插图</p><a href="${b.source}" target="_blank" rel="noreferrer">查看照片来源与授权 ↗</a></div></article>`).join('')}
function renderMonth(){const labels=['越冬期','北迁准备','春迁启动','春迁高峰','抵达北方','繁殖季','育雏季','秋迁启动','秋迁高峰','向南推进','抵达南方','越冬安顿'];$('#monthHeading').textContent=`${['一','二','三','四','五','六','七','八','九','十','十一','十二'][demoState.month-1]}月 · ${labels[demoState.month-1]}`;$('#demoMonth').value=demoState.month}
function render(){renderMap();renderProfile();renderRail();renderMonth()}
$$('.direction-tab').forEach(t=>t.addEventListener('click',()=>{demoState.layout=t.dataset.layout;document.body.className=`layout-${demoState.layout}`;$$('.direction-tab').forEach(x=>x.classList.toggle('active',x===t));let c=LAYOUT_COPY[demoState.layout];$('#layoutIndex').textContent=c[0];$('#layoutDescription').textContent=c[1];$('.demo-caption em').textContent=c[2]}));
$('#demoMonth').addEventListener('input',e=>{demoState.month=+e.target.value;render()});$('#demoPlay').addEventListener('click',()=>{demoState.playing=!demoState.playing;$('#demoPlay').textContent=demoState.playing?'Ⅱ':'▶';clearInterval(demoState.timer);if(demoState.playing)demoState.timer=setInterval(()=>{demoState.month=demoState.month%12+1;render()},900)});
drawCountries();renderAssets();render();
