const MAP_BIRDS={
  "oriental-stork":{name:"东方白鹳",latin:"Ciconia boyciana",photo:"assets/references/oriental-stork.jpg?v=20260802",color:"#2f7a74",intro:"黑白分明的大型湿地涉禽，春季从长江中下游越冬地北返，在中国东北湿地繁殖。",funFact:"GPS 追踪发现了至少四条秋迁路线；即使来自同一巢的幼鸟，也可能选择不同的迁徙路线。",factSource:"https://doi.org/10.1016/j.avrs.2023.100090",route:[[116,29],[120,38],[131,48],[121,37]]},
  "spoon-billed-sandpiper":{name:"勺嘴鹬",latin:"Calidris pygmaea",photo:"assets/references/spoon-billed-sandpiper.jpg",color:"#547f94",intro:"体型很小的极危滨鸟，以独特的勺形嘴辨认；在俄罗斯北极地区繁殖，沿东亚—澳大利西亚迁飞区南下越冬。",funFact:"一只佩戴“H0”脚环的勺嘴鹬，已连续三年回到福建泉州围头湾越冬。",factSource:"https://www.forestry.gov.cn/c/www/dzwzbh/648679.jhtml",route:[[96,17],[112,25],[174,66],[112,25]]},
  "beijing-swift":{name:"北京雨燕",latin:"Apus apus pekinensis",photo:"assets/references/beijing-swift.jpg?v=20260802",color:"#6b7894",intro:"在北京古建筑中繁殖的城市候鸟，长翼、浅叉尾，绝大多数生活都在飞行中完成。",funFact:"地理定位器追踪显示，北京繁殖种群每年往返中国与非洲西南部，全年旅程约三万公里。",factSource:"https://doi.org/10.1186/s40462-022-00329-2",route:[[23,-22],[75,26],[116,40],[43,8]]},
  "bar-headed-goose":{name:"斑头雁",latin:"Anser indicus",photo:"assets/references/bar-headed-goose.jpg",color:"#597c86",intro:"头顶有两道黑色横纹的高原雁类，在青藏高原及蒙古繁殖，部分种群前往印度越冬。",funFact:"研究人员使用太阳能 GPS 卫星发射器，直接记录了斑头雁跨越喜马拉雅山脉时的高度、速度与路线。",factSource:"https://doi.org/10.1073/pnas.1017295108",route:[[78,25],[84,29],[99,37],[88,29]]},
  ...EXTRA_MAP_BIRDS
};
const STYLE_COPY={a:["方案 A · 湿地图鉴","像自然图鉴一样安静，让国家边界退后，鸟群与湿地色成为主角。"],b:["方案 B · 夜航星图","把迁徙看成夜空里的生命信号，鸟群会发出克制的暖色微光。"],c:["方案 C · 东亚折页","像博物馆折页和旧地图，聚焦中国及东亚迁徙通道，编辑感更强。"],d:["方案 D · 观测密度","让网格、记录量和来源成为界面主角，最适合强调数据可信度。"]};
const MONTHS=["一","二","三","四","五","六","七","八","九","十","十一","十二"];
const USER_LOCATION={name:"上海",lng:121.4737,lat:31.2304};
let mapData=null,state={style:"d",bird:"oriental-stork",month:4,timer:null,playing:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function project(lng,lat){return[(lng+180)/360*1000,(90-lat)/180*520]}
function pathRing(ring){return ring.map((p,i)=>`${i?"L":"M"}${project(p[0],p[1]).map(n=>n.toFixed(1)).join(" ")}`).join(" ")+"Z"}
function geoPath(g){if(!g)return"";if(g.type==="Polygon")return g.coordinates.map(pathRing).join(" ");if(g.type==="MultiPolygon")return g.coordinates.flatMap(p=>p.map(pathRing)).join(" ");return""}
function icon(id){return`<svg viewBox="0 0 80 40"><use href="#flock-${id}"/></svg>`}
function routePath(points){return points.map((p,i)=>{const q=project(p[0],p[1]);return`${i?"L":"M"}${q[0]} ${q[1]}`}).join(" ")}
function installExtraIcons(){const sprite=document.querySelector(".symbol-sprite");for(const [id,bird] of Object.entries(EXTRA_MAP_BIRDS)){if(document.querySelector(`#flock-${id}`))continue;sprite.insertAdjacentHTML("beforeend",`<symbol id="flock-${id}" viewBox="0 0 80 40">${EXTRA_ICON_PATHS[bird.iconType]}</symbol>`)}}
function seededOffsets(count,index){const a=[[-17,-4],[-7,-10],[4,-6],[15,-1],[-12,5],[0,3],[12,8],[-4,12],[20,13]];return a[(index+count)%a.length]}
function flockMarkup(cluster,index,birdId,isFallback=false){const p=project(cluster.lng,cluster.lat),count=Math.max(3,Math.round(3+cluster.strength*6)),scale=.85+.3*cluster.strength;let birds="";for(let i=0;i<count;i++){const [dx,dy]=seededOffsets(count,i),opacity=(.62+i/count*.38).toFixed(2);birds+=`<use href="#flock-${birdId}" x="${dx-7}" y="${dy-3.5}" width="14" height="7" opacity="${opacity}"/>`}const evidence=isFallback?`相邻月份范围参考；该网格合计 ${cluster.records} 条邻月抽样记录`:`${cluster.records} 条当月抽样记录落在该聚合网格`;return`<g class="flock-cluster${isFallback?" is-fallback":""}" transform="translate(${p[0]} ${p[1]}) scale(${scale})" style="color:${MAP_BIRDS[birdId].color}">${birds}<title>${evidence}</title></g>`}
function resolveMonthEvidence(speciesData,month){const empty={totalRecords:0,sampledRecords:0,clusters:[]},current=speciesData?.months?.[String(month)]||empty;if(current.clusters?.length)return{current,clusters:current.clusters,isFallback:false,sourceMonths:[]};let before=null,after=null;for(let distance=1;distance<12&&(!before||!after);distance++){const previous=(month-distance+11)%12+1,next=(month+distance-1)%12+1,previousData=speciesData?.months?.[String(previous)],nextData=speciesData?.months?.[String(next)];if(!before&&previousData?.clusters?.length)before={month:previous,data:previousData};if(!after&&nextData?.clusters?.length)after={month:next,data:nextData}}const sources=[before,after].filter(Boolean).filter((item,index,list)=>list.findIndex(x=>x.month===item.month)===index),cells=new Map;for(const source of sources){for(const cluster of source.data.clusters){const key=`${cluster.lng},${cluster.lat}`,existing=cells.get(key)||{lng:cluster.lng,lat:cluster.lat,records:0};existing.records+=cluster.records;cells.set(key,existing)}}const clusters=[...cells.values()],peak=Math.max(1,...clusters.map(c=>c.records));clusters.forEach(c=>c.strength=Math.round(c.records/peak*1000)/1000);return{current,clusters,isFallback:true,sourceMonths:sources.map(s=>s.month)}}
function viewForClusters(clusters){const local={west:65,east:150,south:5,north:60};const inside=clusters.length===0||clusters.every(c=>c.lng>=local.west&&c.lng<=local.east&&c.lat>=local.south&&c.lat<=local.north);if(inside)return{box:"640 60 330 190",label:"中国及附近 · 自动聚焦"};const points=[...clusters.map(c=>project(c.lng,c.lat)),project(local.west,local.north),project(local.east,local.south)];let minX=Math.min(...points.map(p=>p[0]))-30,maxX=Math.max(...points.map(p=>p[0]))+30,minY=Math.min(...points.map(p=>p[1]))-24,maxY=Math.max(...points.map(p=>p[1]))+24;const ratio=1000/520;let width=maxX-minX,height=maxY-minY;if(width/height<ratio){const extra=height*ratio-width;minX-=extra/2;maxX+=extra/2}else{const extra=width/ratio-height;minY-=extra/2;maxY+=extra/2}if(minX<0){maxX-=minX;minX=0}if(maxX>1000){minX-=maxX-1000;maxX=1000}if(minY<0){maxY-=minY;minY=0}if(maxY>520){minY-=maxY-520;maxY=520}return{box:`${Math.max(0,minX).toFixed(1)} ${Math.max(0,minY).toFixed(1)} ${(maxX-minX).toFixed(1)} ${(maxY-minY).toFixed(1)}`,label:"跨区域迁徙 · 自动扩图"}}
async function load(){installExtraIcons();const [countries,gbif]=await Promise.all([fetch("assets/data/countries.geojson").then(r=>r.json()),fetch("assets/data/gbif-monthly-clusters.json?v=20260802-data1").then(r=>r.json())]);mapData=gbif;$("#mapCountries").innerHTML=countries.features.map(f=>`<path class="country ${f.properties.ADMIN==="China"?"china":""}" d="${geoPath(f.geometry)}"><title>${f.properties.ADMIN||""}</title></path>`).join("");const location=project(USER_LOCATION.lng,USER_LOCATION.lat);$("#userLocationHighlight").innerHTML=`<circle class="user-location-wash" cx="${location[0]}" cy="${location[1]}" r="28"/><circle class="user-location-core" cx="${location[0]}" cy="${location[1]}" r="2.8"/><text class="user-location-label" x="${location[0]+7}" y="${location[1]+2.5}">${USER_LOCATION.name}</text>`;renderSpecies();render()}
function renderSpecies(){$("#mapSpecies").innerHTML=Object.entries(MAP_BIRDS).map(([id,b])=>`<button class="${id===state.bird?"active":""}" data-bird="${id}">${icon(id)}<span><b>${b.name}</b><small>${b.latin}</small></span></button>`).join("");$$('[data-bird]').forEach(x=>x.onclick=()=>{state.bird=x.dataset.bird;renderSpecies();render()})}
function render(){if(!mapData)return;const b=MAP_BIRDS[state.bird],speciesData=mapData.species[state.bird],evidence=resolveMonthEvidence(speciesData,state.month),m=evidence.current,copy=STYLE_COPY[state.style],scope=viewForClusters(evidence.clusters),fallbackMonths=evidence.sourceMonths.map(x=>`${MONTHS[x-1]}月`).join("、");$("#styleLabel").textContent=copy[0];$("#designCopy").textContent=b.intro;$("#birdFunFact").textContent=b.funFact||"";$("#funFactBox").hidden=!b.funFact;$("#birdFactSource").href=b.factSource||"#";$("#monthTitle").textContent=`${MONTHS[state.month-1]}月的${b.name}鸟群分布`;$("#scopeLabel").textContent=scope.label;$("#recordSummary").textContent=evidence.isFallback?`GBIF 本月无可用记录 · 显示${fallbackMonths}范围参考`:`GBIF 收录 ${m.totalRecords.toLocaleString()} 条 · 本图抽样 ${m.sampledRecords} 条`;$("#sampleCount").textContent=evidence.isFallback?`0 条 · ${fallbackMonths}参考`:`${m.sampledRecords} 条`;$("#birdPhoto").src=b.photo;$("#birdPhoto").alt=`${b.name}参考照片`;$("#birdName").textContent=b.name;$("#birdLatin").textContent=b.latin;$("#birdIcon").innerHTML=icon(state.bird);$("#birdIcon").style.color=b.color;$("#flockLayer").innerHTML=evidence.clusters.map((c,i)=>flockMarkup(c,i,state.bird,evidence.isFallback)).join("");$("#researchRoute").innerHTML="";$("#mapMonth").value=state.month;$("#dataWarning").textContent=evidence.isFallback?`注意：${b.name}该月没有可用的 GBIF 聚合记录。为保持年度连续可读，鸟群显示最近前后有记录月份（${fallbackMonths}）的范围参考，不代表该月实测位置。`:m.sampledRecords<30?`注意：${b.name}该月公开记录很少，图上疏密主要反映公开记录，不代表种群数量。`:"";$("#flockMap").setAttribute("viewBox",scope.box)}
$$('[data-style]').forEach(btn=>btn.onclick=()=>{state.style=btn.dataset.style;document.body.className=`map-style-${state.style}`;$$('[data-style]').forEach(x=>x.classList.toggle("active",x===btn));render()});$("#mapMonth").oninput=e=>{state.month=+e.target.value;render()};$("#mapPlay").onclick=()=>{state.playing=!state.playing;$("#mapPlay").textContent=state.playing?"Ⅱ":"▶";clearInterval(state.timer);if(state.playing)state.timer=setInterval(()=>{state.month=state.month%12+1;render()},950)};load();
